### ISSUE TITLE
Forge version 1.1.4 Broken duplicate recipe

### ISSUE THREAD

**Issue by TynotWolfDragon** [AverageAnime/create-food-1.20.1#44] opened 2024-10-25 11:42 UTC
Sliced bread has a broken recipe, but it's broken. The recipe returns nothing, deleting the bread. 

![image](https://github.com/user-attachments/assets/0cba4942-7848-4b25-827a-206ad93b5372)

**Comment by PurgeWicks** [comment] 2024-11-16 21:04
can confirm this is an issue. wish i knew there was a way to make the other (real) recipe priority.

**Comment by PurgeWicks** [comment] 2024-11-20 05:49
i have finally found what was wrong. it is a recipe bug with this forge mod named _Delightful_ (https://modrinth.com/mod/delightful) versions 3.5.7 and up. not sure how i would go around this keeping both mods atm.

**Comment by AverageAnime** [comment] 2024-11-20 17:13
Closing thread, as this is not caused by Create: Food. Here is the issue on Delightful, for more info: https://github.com/brnbrd/Delightful/issues/98

Until the recipe is fixed within the mod itself, you can simply remove the recipe with a datapack or other method.

**Closed as not planned by AverageAnime** 2024-11-20 17:13 UTC
